player input + movement complete
pistolPeterson/project-sumin-prototype-repo pull request #5
Opened 2024-07-28 06:04 UTC by Raaee

check it sil vous plait :))))

completed movement and added inputs

2024-07-28 11:32 UTC, pistolPeterson commented on Assets/Art/UI/cameraBorder.png
camera border. sigh

2024-07-28 11:44 UTC, pistolPeterson requested changes
- smooth movement 
- add a simple visual representation of the shield, maybe the player visual changes color 
- simplify/cleanup input system

2024-07-28 11:44 UTC, pistolPeterson commented on Assets/Scripts/Player Input/PlayerMovement.cs
> +    [SerializeField] private float upperPositionConstraint = 8f;
the constraints would never be unbalanced, make it one variable please

2024-07-28 11:44 UTC, pistolPeterson commented on Assets/Scripts/Player Input/InputManager.cs
> +    private IEnumerator Moving() {
wait we have to write our own code to allow multiple button press??????

2024-07-28 11:44 UTC, pistolPeterson commented on Assets/Scripts/Player Input/PlayerMovement.cs
> +    {MovePlayerUp(moveDistance);}
as discussed, make the movement smooth. make the default speed slower than usual so the blessings can make it faster in the future

2024-07-28 11:44 UTC, pistolPeterson commented on Assets/Scripts/Player Input/InputManager.cs
> +        StartCoroutine(Moving());
this is input system, it should not be named **moving**

2024-07-30 06:26 UTC, Raaee commented on Assets/Scripts/Player Input/PlayerMovement.cs
> +    [SerializeField] private float upperPositionConstraint = 8f;
done.

2024-07-30 12:28 UTC, pistolPeterson requested changes
unity nodemap scene doesnt work. unplayable 2/10
code does look good i guess, sigh

2024-07-30 20:41 UTC, pistolPeterson approved these changes
works great, good to go

2024-07-30 20:41 UTC, merged